# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8-browsers
#     steps:
#       - run:
#           name: Install dependencies
#           command: |
#             npm install
#       - run:
#           name: Install cypress
#           command: |
#             npm install cypress cypress-cucumber-preprocessor
#       - run:
#           name: Start server
#           command: |
#             npm start
#       - run:
#           name: run cypress tests
#           command: |
#             npm run s-test
#       - store_artifacts:
#           path: '.'



version: 2
jobs:
  build:
    docker:
          - image: circleci/node:8-browsers
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Install cypress
      - run: npm install cypress cypress-cucumber-preprocessor

      # Start server
      - run: npm start

      # run tests!
      - run: npm run s-test
