version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Install cypress
          command: |
            npm install cypress cypress-cucumber-preprocessor
      - run:
          name: run cypress tests
          command: |
            ./node_modules//.bin/cypress run
      - store_artifacts:
          path: '.'
